### PR TITLE
Create ipis_colp_georesults and change address normalization

### PR DESCRIPTION
**Pull request by mgraber**
#100 #107 

Known issue:
Calls to function 1B return non-NULL 1E reason codes for 1E GRC of 00. This field seems to be picking up the 1A reason code. Additionally, the warning codes returned are always empty, even in cases where a GRC of 01 suggests that there should be a warning. See examples in the code block below.

To-do feedback from Lynn:
- [x] `colp_unmapped.csv`: Deprecate 
- [x]  `ipis_colp_geoerrors.csv`:
    + Rename to "ipis_colp_georesults.csv"
    + Switch order of 1e and 1a in parser
    + Include warnings, not just errors

> The grc and rsn fields aren’t correct. There are a lot of fields with grc_1a = 00 and a non-blank value for rsn_1a, which makes no sense since rsn is populated when grc = 01. Also, the values seem to be switched. In the below examples, the correct values from GOAT are in parentheses

    **358 LIVONIA AVENUE, Brooklyn – grc_1a = 00 (01), rsn_1a = 8 (8), grc_1e = 01 (00), rsn_1e = 8 (blank)**
    Relevant returns from geosupport python bindings call to 1B `g['1B'](street_name='LIVONIA AVENUE', house_number='358', borough='3', mode='regular')`:

    ```
    {
    'Geosupport Return Code (GRC)': '00',
    'Geosupport Return Code 2 (GRC 2)': '01',
    'Message': '',
    'Message 2': 'INPUT ADDRESS IS A PSEUDO-ADDRESS',
    'Reason Code': '8',
    'Reason Code 2': '8',
    'Reason Code Qualifier': '',
    'Reason Code Qualifier 2': '',
    'Return Code': '01',
    'Warning Code': '',
    'Warning Code 2': '',
    }
    ```
    **1452 BROADWAY, Brooklyn – grc_1a = 00 (42), grc_1e = 42 (00)**
    Relevant returns from geosupport python bindings call to 1B `g['1B'](street_name='BROADWAY', house_number='1452', borough='3', mode='regular')`:

    ```
    {
    'Geosupport Return Code (GRC)': '00',
    'Geosupport Return Code 2 (GRC 2)': '42',
    'Message': '',
    'Message 2': 'ADDRESS NUMBER OUT OF RANGE',
    'Reason Code': '',
    'Reason Code 2': '',
    'Reason Code Qualifier': '',
    'Return Code': '42',
    'Warning Code': '',
    'Warning Code 2': '',
    }
    ```
    **1815 STERLING PLACE, Brooklyn – grc_1a = 00 (00), rsn_1a = 8 (blank), grc_1e = 01 (00), rsn_1e = 8 (blank)**
     Relevant returns from geosupport python bindings call to 1B `g['1B'](street_name='STERLING PLACE', house_number='1815', borough='3', mode='regular')`:

    ```
    {
    'Geosupport Return Code (GRC)': '00',
    'Geosupport Return Code 2 (GRC 2)': '01',
    'Message': '',
    'Message 2': 'INPUT ADDRESS IS A PSEUDO-ADDRESS',
    'Reason Code': '8',
    'Reason Code 2': '8',
    'Reason Code Qualifier': '',
    'Reason Code Qualifier 2': '',
    'Return Code': '01',
    'Warning Code': '',
    'Warning Code 2': '',
    }
    ```
**SEE PAGE 82 OF THE [UPG](https://www1.nyc.gov/assets/planning/download/pdf/data-maps/open-data/upg.pdf?r=16b)**
- [x] `modified_hnums.csv`: Add "ipis_" prefix, and add any fields necessary to identify records in the source data
- [x] `unmapped_airrights.csv`: Deprecate

### CODE REVIEW

**Review by AmandaDoyle — COMMENTED** [review]
This is returning the right things so it can be merged in, but here are my comments/questions before doing so.  Happy to hop on a call to talk this through
Is it worth adding a `ipis_modified_streetnames` QAQC table?
Should we remove warn fields from 'ipis_colp_georesults' table since it's always NULL?
Should we remove and rename fields in `ipis_colp_geoerrors` to conform to the schema we agreed on? 
https://github.com/NYCPlanning/db-colp/issues/107#issuecomment-794610154
What is display_hnum in `ipis_colp_georesults`?  
Should we limit `ipis_colp_georesults` to records where either GRC <> 00?

**Comment by mgraber** [comment]
@AmandaDoyle 
> Is it worth adding a `ipis_modified_streetnames` QAQC table?

Maybe. Let's reach out to Lynn to confirm.

> Should we remove warn fields from 'ipis_colp_georesults' table since it's always NULL?

I would guess yes, but this depends on how we resolve the issue with Linux Geosupport returning unexpected values.

> Should we remove and rename fields in `ipis_colp_geoerrors` to conform to the schema we agreed on?
> [#107 (comment)](https://github.com/NYCPlanning/db-colp/issues/107#issuecomment-794610154)

This means removing `dcas_ipis_uid`, `bill_bbl_1b`, `display_hnum`,  and `PARCELNAME`? The uid and display hnum get used by other tables, so we'll continue to create them. We can make a modified export version of `ipis_colp_georesults` if including them is confusing.

> What is display_hnum in `ipis_colp_georesults`?

This is the house number that gets displayed in COLP. The result of the light string cleaning.

> Should we limit `ipis_colp_georesults` to records where either GRC <> 00?

Perhaps? I created this as a master table since it gets used for multiple purposes. But again, we can make different export views once we get logic from Lynn and GRU.

**Comment by AmandaDoyle** [comment]
@mgraber  Thanks for these responses.  I'll reach out to Lynn about creating a `ipis_modified_streetnames`.  Based on your responses this is good to merge in and we can build off of it.

**Comment by mgraber** [comment]
Also addresses:
#97 #98 #100

**Pull request merged**
