### PR TITLE
Create Issue template for COLP

### PR DESCRIPTION
**Pull request by mbh329**
Addresses issue #228 . One reviewer ⭐ 

Add issue template for the dataloading step to track data updates better and help standardize build processes for our data products. For every COLP build, this issue should be created and the list of data updated via data library should be ingested, checked to make sure data is as expected, and checked off the list.

### CODE REVIEW

**Review by td928 — APPROVED** [review]
lgtm

**Comment by mbh329** [comment]
@damonmcc adding you as a reviewer in this PR even though Te had already approved it. Generally we try create issue templates for input data into data products so that for each build we are tracking that we have recent data. Let me know if you have questions about this

**Comment by mbh329** [comment]
Typically I should have already merged this but this fell off my radar but might be a good exercise in understanding how we typically approach a data product build especially patterns that we find useful

**Comment by damonmcc** [comment]
@mbh329 appreciate being tagged in! I like this approach of using issues to track or trigger data updates, it's part of my initial pass at "standard files" in the new PLUTO + zoning repo (https://github.com/NYCPlanning/db-pluto-zola/issues/3)

**Review by damonmcc — APPROVED** [review]

**Pull request merged**
