### PR TITLE
Send qaqc files to nested folder

### PR DESCRIPTION
**Pull request by SashaWeinstein**
Easy PR, one reviewer 📂 
Addresses half of issue #204, don't know if we need to address the other half of that issue
This and PR #206 should make it easy to add new queries for the COLP QAQC page

### CODE REVIEW

**Review by abrieff — APPROVED** [review]
lgtm

**Comment by SashaWeinstein** [comment]
Addressed merge conflict. Think that the call to `qc_geospatial_check` should happen in the `03_qaqc.sh` unless there's a reason it needs to be in the build step? @Oysters1874

**Comment by SashaWeinstein** [comment]
Ok word. I'm going to move it to the qaqc in this PR

**Review by Oysters1874 — APPROVED** [review]
LGTM

**Review by abrieff — APPROVED** [review]

**Pull request merged**
